version: "3" 
services:
  db:
    build: 
      context: .
      target: db
    container_name: DockerDB
    ports:
      - 1521:1521 
      - 5500:5500 
    environment:
      - ORACLE_SID=DockerDB 
      - ORACLE_PDB=DockerPDB 
      - ORACLE_PWD=Welcome1
  app: 
    build: 
      context: .
      target: app
    container_name: DockerApp
    ports:
      - 8080:8080
    environment:
      - DB_URL=localhost:1521/DockerDB
      - DB_USERNAME=parser
      - DB_PASSWORD=parser
    depends_on:
      - db