version: "3" 
services:
  InfraDB:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    ports:
      - 1521:1521 
      - 5500:5500 
    environment:
      - ORACLE_SID=DockerDB 
      - ORACLE_PDB=DockerPDB 
      - ORACLE_PWD=Welcome1
  parser: 
    image: parsertool
    ports:
      - 8080:8080
    environment:
      - DB_URL=localhost:1521/DockerDB
      - DB_USERNAME=parser
      - DB_PASSWORD=parser
    depends_on:
      - InfraDB