version: "3" 
services:
  InfraDB:
    env_file: C:\Users\Mohammad\IdeaProjects\ParserTool\env.txt
    image: container-registry.oracle.com/database/enterprise:12.2.0.1
    ports:
      - 1521:1521 
      - 5500:5500 
    shm_size: 2GB 
    environment:
      - ORACLE_PWD=sys
      - DB_PASSWD=sys
  parser: 
    image: parse-image:latest 
    ports:
      - 8080:8080
    environment:
      - DB_URL=localhost:1521/orcl
      - DB_USERNAME=parser
      - DB_PASSWORD=parser
    depends_on:
      - InfraDB